### ISSUE TITLE
How to get the correctly indexPath for [UICollectionView selectItemAtIndexPath:animated:scrollPosition:];

### ISSUE THREAD

**Issue by iOkay** [masoapps/infinite-uicollectionview#5]

**Comment by masonlamy** [comment]
Hi iOkay,

If you look in InfiniteCollectionView.swift, there is a function defined:

`private func getCorrectedIndex(indexToCorrect: Int) -> Int`

Passing your index into this function (either by making it public or copying the function into your code base) should return an index which gives you the correct index for use with indexPath.

Kind regards,
Mason
